project:
  type: website

website:
  title: "Concept_Showcase_Jia"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Exploratory Analysis"
        href: ExploratoryAnalysis.qmd
      - text: "Clustering Analysis"
        href: ClusteringAnalysis.qmd
      - text: "Network Analysis"
        href: NetworkAnalysis.qmd
      - text: "Policy Implications"
        href: about.qmd




